from . import res_partner_inherited
from . import status_contrato
from . import account_analytic_account_inherited
from . import adesao
from . import plano
from . import grupo_servico
from . import modo_aquisicao
from . import status_adesao
from . import conexao_cliente
from . import manifestacao_atendimento
from . import grupo_atendimento
from . import tipo_atendimento
from . import protocolo
from . import atendimento
from . import status_atendimento
from . import modo_contato
from . import sla
from . import sla_zabbix
from . import localidade
from . import status_ocorrencia
from . import tipo_ocorrencia
from . import ocorrencia
from . import contato_localidade
from . import abre_fecha_ocorrencia
from . import lote_ocorrencias
from . import lote_abre_fecha_ocorrencias
from . import plano_cidade
from . import contato_cliente