#coding=utf-8

{
    'name': 'Suporte',
    'category': 'Uncategorized',
    'summary': 'Módulo customizado para o setor de suporte da Cinte.',
    'version': '1.1',
    'description': "Módulo customizado para o setor de suporte da Cinte.",
    'author': 'Edson Junior',
    'depends': ['base','mail','contacts','account_analytic_analysis','l10n_br_hr','redes'],
    'installable': True,
    'data': [
        'views/menu.xml',
        'security/suporte_security.xml',
        'views/res_partner_notificacoes.xml',
        'views/res_partner_form_inherited.xml',
        'views/res_partner_form_acesso.xml',
        'views/status_contrato_form.xml',
        'views/status_contrato_notificacoes.xml',
        'views/status_contrato_tree.xml',
        'views/status_adesao_form.xml',
        'views/status_adesao_notificacoes.xml',
        'views/status_adesao_tree.xml',
        'views/plano_form.xml',
        'views/plano_notificacoes.xml',
        'views/plano_tree.xml',
        'views/grupo_servico_form.xml',
        'views/grupo_servico_notificacoes.xml',
        'views/grupo_servico_tree.xml',
        'views/modo_aquisicao_form.xml',
        'views/modo_aquisicao_notificacoes.xml',
        'views/modo_aquisicao_tree.xml',
        'views/conexao_cliente_form.xml',
        'views/conexao_cliente_tree.xml',
        'views/conexao_cliente_search.xml',
        'views/adesao_form.xml',
        'views/adesao_tree.xml',
        'views/adesao_search.xml',
        'views/adesao_graph.xml',
        'views/report_contrato.xml',
        'views/report_adesao.xml',
        'views/account_analytic_account_form.xml',
        'views/account_analytic_account_graph.xml',
        'views/manifestacao_atendimento_form.xml',
        'views/manifestacao_atendimento_tree.xml',
        'views/grupo_atendimento_form.xml',
        'views/grupo_atendimento_tree.xml',
        'views/tipo_atendimento_form.xml',
        'views/tipo_atendimento_tree.xml',
        'views/atendimento_form.xml',
        'views/atendimento_kanban.xml',
        'views/atendimento_tree.xml',
        'views/atendimento_graph.xml',
        'views/status_atendimento_form.xml',
        'views/status_atendimento_tree.xml',
        'views/protocolo_sequencia.xml',
        'views/modo_contato_form.xml',
        'views/modo_contato_tree.xml',
        'views/localidade_form.xml',
        'views/localidade_tree.xml',
        'views/sla_form.xml',
        'views/sla_tree.xml',
        'views/report_sla.xml',
        'views/sla_zabbix_form.xml',
        'views/sla_zabbix_tree.xml',
        'views/report_sla_zabbix.xml',
        'views/status_ocorrencia_form.xml',
        'views/tipo_ocorrencia_form.xml',
        'views/ocorrencia_sequencia.xml',
        'views/ocorrencia_form.xml',
        'views/ocorrencia_kanban.xml',
        'views/ocorrencia_tree.xml',
        'views/ocorrencia_graph.xml',
        'views/abre_fecha_ocorrencia_form.xml',
        'views/email_template_abre_fecha_ocorrencia.xml',
        'views/email_template_abre_ocorrencia.xml',
        'views/email_template_chamado_imputavel.xml',
        'views/lote_ocorrencias_tree.xml',
        'views/lote_ocorrencias_form.xml',
        'views/lote_abre_fecha_ocorrencias_form.xml',
        'views/plano_cidade_form.xml'
    ]
}